apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: nginx-tgb
  namespace: ingress-nginx
spec:
  serviceRef:
    name: nginx-ingress-nginx-controller
    port: 80
  targetGroupARN: TARGET_GROUP_ARN_PLACEHOLDER
  targetType: ip
